import { assert, DEFAULT_ROOT, MAX_OUTPUT_BYTES, object, PROTOCOL_VERSION, VERSION } from './core.mjs';
import { getCatalog } from './catalog.mjs';
import { resolve } from './resolve.mjs';
import { build, check, validate } from './plugins.mjs';

export const HELP = `AgentPatrol ${VERSION} (Node.js 22+, Patrol protocol ${PROTOCOL_VERSION})

agentpatrol catalog [--root DIR]          Read a catalog request from JSON stdin
agentpatrol resolve [--root DIR]          Read a resolution request from JSON stdin
agentpatrol build [--root DIR] [--out DIR] Build portable persona and profile plugins
agentpatrol check [--root DIR] [--out DIR] Check generated byte-for-byte drift
agentpatrol validate [--root DIR] [--out DIR] Validate sources and generated plugins
agentpatrol --version
agentpatrol --help

Default root: installed package; default output: ROOT/plugins.
catalog stdin: {"protocolVersion":"1.0"}
resolve stdin: {"protocolVersion":"1.0","persona":"developer","profiles":["react"]}
Stdin is limited to 64 KiB and 5 seconds; JSON output to 1 MiB.
Unknown fields, commands, options, personas and profiles fail nonzero.
`;

async function request(input) {
  let timer;
  const reading = (async () => {
    let bytes = 0;
    const chunks = [];
    for await (const chunk of input) {
      const buffer = Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk);
      bytes += buffer.length;
      assert(bytes <= 64 * 1024, 'JSON stdin exceeds 64 KiB');
      chunks.push(buffer);
    }
    return JSON.parse(new TextDecoder('utf-8', { fatal: true }).decode(Buffer.concat(chunks)));
  })();
  try {
    return await Promise.race([reading, new Promise((_, reject) => {
      timer = setTimeout(() => { reject(new Error('JSON stdin timed out after 5 seconds')); input.destroy(); }, 5000);
    })]);
  } finally { clearTimeout(timer); }
}

export async function main(argv = process.argv.slice(2)) {
  if (argv.length === 1 && argv[0] === '--help') { process.stdout.write(HELP); return; }
  if (argv.length === 1 && argv[0] === '--version') { process.stdout.write(`${VERSION}\n`); return; }
  const [command, ...args] = argv;
  assert(['catalog', 'resolve', 'build', 'check', 'validate'].includes(command), 'Expected catalog, resolve, build, check or validate; see --help');
  const options = { root: DEFAULT_ROOT };
  const seen = new Set();
  for (let index = 0; index < args.length; index += 2) {
    const flag = args[index];
    assert(flag === '--root' || (flag === '--out' && ['build', 'check', 'validate'].includes(command)), `Unknown option: ${flag}`);
    assert(!seen.has(flag), `Duplicate option: ${flag}`);
    assert(args[index + 1] && !args[index + 1].startsWith('--'), `Missing value: ${flag}`);
    seen.add(flag);
    options[flag.slice(2)] = args[index + 1];
  }
  let result;
  if (command === 'catalog' || command === 'resolve') {
    const input = await request(process.stdin);
    if (command === 'catalog') {
      object(input, ['protocolVersion'], 'catalog request');
      assert(input.protocolVersion === PROTOCOL_VERSION, `protocolVersion must be ${PROTOCOL_VERSION}`);
      result = await getCatalog(options);
    } else result = await resolve(input, options);
  } else result = await ({ build, check, validate })[command](options);
  const serialized = `${JSON.stringify(result)}\n`;
  assert(Buffer.byteLength(serialized) <= MAX_OUTPUT_BYTES, 'JSON output exceeds 1 MiB');
  process.stdout.write(serialized);
}
